table Calendrier

	column Date
		dataType: dateTime
		isKey
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: Date

	column Annee
		dataType: int64
		summarizeBy: none
		sourceColumn: Annee

	column Mois
		dataType: int64
		summarizeBy: none
		sourceColumn: Mois

	column MoisNom
		dataType: string
		summarizeBy: none
		sourceColumn: MoisNom
		sortByColumn: Mois

	column AnneeMois
		dataType: string
		summarizeBy: none
		sourceColumn: AnneeMois

	column Trimestre
		dataType: string
		summarizeBy: none
		sourceColumn: Trimestre

	partition Calendrier = m
		mode: import
		source =
				let
					Deb = #date(2008, 1, 1),
					Fin = #date(2027, 12, 31),
					N = Duration.Days(Fin - Deb) + 1,
					Liste = List.Dates(Deb, N, #duration(1, 0, 0, 0)),
					T = Table.FromList(Liste, Splitter.SplitByNothing(), {"Date"}),
					Typ = Table.TransformColumnTypes(T, {{"Date", type date}}),
					Annee = Table.AddColumn(Typ, "Annee", each Date.Year([Date]), Int64.Type),
					Mois = Table.AddColumn(Annee, "Mois", each Date.Month([Date]), Int64.Type),
					MoisNom = Table.AddColumn(Mois, "MoisNom", each Date.ToText([Date], "MMMM", "fr-FR"), type text),
					AM = Table.AddColumn(MoisNom, "AnneeMois", each Date.ToText([Date], "yyyy-MM"), type text),
					Tri = Table.AddColumn(AM, "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Date])), type text)
				in
					Tri

	annotation PBI_ResultType = Table
