table Cours_Actions

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: Date

	column Ticker
		dataType: string
		summarizeBy: none
		sourceColumn: Ticker

	column Ouverture
		dataType: double
		formatString: #,0
		summarizeBy: none
		sourceColumn: Ouverture

	column Plus_Haut
		dataType: double
		formatString: #,0
		summarizeBy: none
		sourceColumn: Plus_Haut

	column Plus_Bas
		dataType: double
		formatString: #,0
		summarizeBy: none
		sourceColumn: Plus_Bas

	column Cloture
		dataType: double
		formatString: #,0
		summarizeBy: none
		sourceColumn: Cloture

	column Volume_Titres
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: Volume_Titres

	column Volume_FCFA
		dataType: double
		formatString: #,0
		summarizeBy: sum
		sourceColumn: Volume_FCFA

	column Variation_Pct
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Variation_Pct

	measure 'Dernier Cours' = CALCULATE(LASTNONBLANKVALUE(Calendrier[Date], MAX(Cours_Actions[Cloture])))
		formatString: #,0

	measure 'Premier Cours' = CALCULATE(FIRSTNONBLANKVALUE(Calendrier[Date], MAX(Cours_Actions[Cloture])))
		formatString: #,0

	measure 'Perf Période %' = DIVIDE([Dernier Cours] - [Premier Cours], [Premier Cours])
		formatString: 0.0%

	measure 'Plus Haut Période' = MAX(Cours_Actions[Plus_Haut])
		formatString: #,0

	measure 'Plus Bas Période' = MIN(Cours_Actions[Plus_Bas])
		formatString: #,0

	measure 'Volume Titres' = SUM(Cours_Actions[Volume_Titres])
		formatString: #,0

	measure 'Volume FCFA' = SUM(Cours_Actions[Volume_FCFA])
		formatString: #,0

	partition Cours_Actions = m
		mode: import
		source =
				let
					liste = fnListerDossier("actions"),
					csvOnly = Table.SelectRows(liste, each Text.EndsWith([name], "_historique.csv")),
					avecTicker = Table.AddColumn(csvOnly, "Ticker", each Text.BeforeDelimiter([name], "_historique"), type text),
					avecTab = Table.AddColumn(avecTicker, "Tab", each
						Table.PromoteHeaders(
							Csv.Document(fnContenu("data/actions/" & [name]), [Delimiter = ";", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
							[PromoteAllScalars = true])),
					garde = Table.SelectColumns(avecTab, {"Ticker", "Tab"}),
					exp = Table.ExpandTableColumn(garde, "Tab", {"Date", "Ouverture", "Plus_Haut", "Plus_Bas", "Cloture", "Volume_Titres", "Volume_FCFA", "Variation_Pct"}),
					types = Table.TransformColumnTypes(exp, {
						{"Date", type date},
						{"Ouverture", type number}, {"Plus_Haut", type number}, {"Plus_Bas", type number}, {"Cloture", type number},
						{"Volume_Titres", Int64.Type}, {"Volume_FCFA", type number}, {"Variation_Pct", type number}
					}, "fr-FR")
				in
					types

	annotation PBI_ResultType = Table
