table Indices_Info

	column Symbol
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: Symbol

	column Nom
		dataType: string
		summarizeBy: none
		sourceColumn: Nom

	column ISIN
		dataType: string
		summarizeBy: none
		sourceColumn: ISIN

	partition Indices_Info = m
		mode: import
		source =
				let
					liste = fnListerDossier("indices"),
					only = Table.SelectRows(liste, each Text.EndsWith([name], "_info.json")),
					sym = Table.AddColumn(only, "Symbol", each Text.BeforeDelimiter([name], "_info"), type text),
					rec = Table.AddColumn(sym, "R", each Json.Document(fnContenu("data/indices/" & [name]))),
					nom = Table.AddColumn(rec, "Nom", each try [R][Name] otherwise [Symbol], type text),
					isin = Table.AddColumn(nom, "ISIN", each try [R][ISIN] otherwise null, type text),
					garde = Table.SelectColumns(isin, {"Symbol", "Nom", "ISIN"})
				in
					garde

	annotation PBI_ResultType = Table
